menu:
  Home: /archives
  Archives: /
  Myself: /

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter:
github: awesomeric


fancybox: true
google_analytics:
rss:
duoshuo_shortname: awesomeric